backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "صورة المنتج", name: "image", widget: "image" }
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "السعر ($)", name: "price", widget: "number", value_type: "float" }
      - { label: "الكمية المتوفرة", name: "quantity", widget: "number", default: 1 }
      - { label: "غير متوفر بالمخزن (شطب)", name: "out_of_stock", widget: "boolean", default: false }
      - { label: "القسم", name: "category", widget: "select", options: ["يد التحكم", "الشبكات والراوترات", "كمبيوتر وملحقاته"] }
